- name: Create temp dir on jump host
  ansible.builtin.shell: mktemp -d /tmp/nginx-setup-XXXXXX
  register: tmp_dir
  changed_when: true

- name: Set script path
  set_fact:
    remote_script_path: "{{ tmp_dir.stdout }}/install_nginx.sh"

- name: Copy nginx install script to jump host
  ansible.builtin.template:
    src: install_nginx.sh.j2
    dest: "{{ remote_script_path }}"
    mode: '0755'
  vars:
    remote_host: "{{ item }}"

- name: Run install script on private host {{ item }}
  ansible.builtin.shell: |
    sudo ssh -o StrictHostKeyChecking=no {{ item }} {{ remote_script_path }}
  register: install_result
  vars:
    remote_host: "{{ item }}"

- name: Show install result from {{ item }}
  ansible.builtin.debug:
    var: install_result.stdout_lines
  
