- name: DEBUG — Role is loaded
  debug:
    msg: "✅ delegated_ssh_nginx role is running"

- name: Loop over private hosts
  include_tasks: install_nginx.yml
  loop: "{{ groups['private_hosts'] }}"
  loop_control:
    loop_var: item
    label: "{{ item }}"
